// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEytHoODhIS_pUdT_bctv23zFzzLP5BJY',
    appId: '1:201988425291:web:1800bb0c005af4950d2fce',
    messagingSenderId: '201988425291',
    projectId: 'firestore-flutter-b5e6c',
    authDomain: 'firestore-flutter-b5e6c.firebaseapp.com',
    storageBucket: 'firestore-flutter-b5e6c.appspot.com',
    measurementId: 'G-NZ5N1FEK5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9kz2Ctds58nQGhdighfwPrBMIpN2LOVA',
    appId: '1:201988425291:android:21c6227973fb392d0d2fce',
    messagingSenderId: '201988425291',
    projectId: 'firestore-flutter-b5e6c',
    storageBucket: 'firestore-flutter-b5e6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuLToIvJ3OUdwh25dr7oZYWZSrBuwU6U0',
    appId: '1:201988425291:ios:4eecf8c0262de2600d2fce',
    messagingSenderId: '201988425291',
    projectId: 'firestore-flutter-b5e6c',
    storageBucket: 'firestore-flutter-b5e6c.appspot.com',
    iosClientId: '201988425291-vbide2scecb0a4po2nbg84muregi2lh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuLToIvJ3OUdwh25dr7oZYWZSrBuwU6U0',
    appId: '1:201988425291:ios:4eecf8c0262de2600d2fce',
    messagingSenderId: '201988425291',
    projectId: 'firestore-flutter-b5e6c',
    storageBucket: 'firestore-flutter-b5e6c.appspot.com',
    iosClientId: '201988425291-vbide2scecb0a4po2nbg84muregi2lh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestorage',
  );
}
